#!/usr/bin/env node
// Write Dockerfile, .dockerignore, docker-compose.yml, docker/nginx.conf and
// .github/workflows/docker.yml into every repo listed in fleet.json.
//
// Usage:
//   node scripts/gen-docker.mjs [--projects DIR] [--only repo,repo] [--dry-run]
//
// Everything this emits is derived from fleet.json. Nothing is sniffed from the
// target repo at generation time, because a generator that guesses is a
// generator that quietly guesses wrong for one repo out of twenty-eight and
// nobody notices until an image is pulled.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateNginx } from './headers-to-nginx.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');

const args = process.argv.slice(2);
const opt = (name, fallback) => {
  const i = args.indexOf(name);
  return i === -1 ? fallback : args[i + 1];
};
const PROJECTS = opt('--projects', join(process.env.HOME, 'Projects'));
const ONLY = opt('--only', null)?.split(',').map((s) => s.trim());
const DRY = args.includes('--dry-run');

const fleet = JSON.parse(readFileSync(join(ROOT, 'fleet.json'), 'utf8'));
const unraid = JSON.parse(readFileSync(join(ROOT, 'unraid.json'), 'utf8'));
const REGISTRY = fleet.registry;

// GitHub Actions minutes are only billed for private repositories. Public repos
// build for free and can afford a pull_request trigger; private ones would pay
// for a full image build on every push to every branch of every PR, which for
// the Rust services is minutes each time. They build on landed changes only.
const PRIVATE_TRIGGER_NOTE = `  # No pull_request trigger: this repo is private, so its Actions minutes are
  # billed. Building on every PR push would spend quota re-proving a Dockerfile
  # that has not changed. Use workflow_dispatch to test a build before merging.`;

/** An image is billed if any repo publishing it is private. */
function billsMinutes(repo) {
  return Object.values(unraid.apps).some(
    (a) => a.repo === repo && a.visibility === 'private',
  );
}

const DEFAULT_NODE = '22';
const NGINX_BASE = 'nginx:1.27-alpine';
const RUST_BASE = 'rust:1-slim';
const RUNTIME_BASE = 'debian:bookworm-slim';

const written = [];
const skipped = [];

function write(repoDir, relPath, contents) {
  const full = join(repoDir, relPath);
  if (DRY) {
    written.push(`[dry] ${full}`);
    return;
  }
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, contents);
  written.push(full);
}

/** Shared header for every generated file, so nobody hand-edits one by mistake. */
function banner(comment, repo) {
  return `${comment} Generated by stoatworks-unraid/scripts/gen-docker.mjs from fleet.json.
${comment} Repo: ${repo}. Edit fleet.json and regenerate — direct edits are overwritten.
`;
}

// ---------------------------------------------------------------------------
// nginx-served images (static-prebuilt and static-build)
// ---------------------------------------------------------------------------

function nginxRuntimeStage(app, copyFrom) {
  const note = app.note ? `\n# NOTE: ${wrap(app.note, 76, '# ')}\n` : '';
  return `${note}
FROM ${NGINX_BASE}

# The snippets directory is not in the nginx:alpine image; conf.d is, but a file
# dropped there is auto-included into the http block, which would apply these
# add_header lines globally instead of per-location and defeat the point.
RUN mkdir -p /etc/nginx/snippets

# Extend the MIME map rather than replacing it. nginx 1.27's mime.types already
# maps .wasm but still has no .mjs, and the obvious fix — a \`types { }\` block in
# the server config — REPLACES the inherited map instead of adding to it, which
# silently demotes every .css and .js to application/octet-stream. Appending to
# the file itself is the only form that adds. The \`nginx -t\` below is what
# catches it if this sed ever stops matching.
RUN sed -i 's|^}$|    text/javascript                        mjs;\\n}|' /etc/nginx/mime.types \\
    && grep -q 'mjs;' /etc/nginx/mime.types

COPY docker/stoatworks-headers.conf /etc/nginx/snippets/stoatworks-headers.conf
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

${copyFrom}

# _headers is a Cloudflare edge directive file. nginx does not read it, and
# serving it would publish the CSP as a static asset for no reason. Its contents
# have already been translated into the config above.
RUN rm -f /usr/share/nginx/html/_headers /usr/share/nginx/html/_redirects

# Fail the build on a bad config rather than at container start. nginx.conf is
# generated from a _headers file, and a header value that needs quoting
# differently would otherwise produce an image that builds green and then
# crash-loops on deploy. This is also the only syntax check these configs get:
# they were authored on a machine with no nginx and no container runtime.
RUN nginx -t

EXPOSE 80

# busybox wget, present in the alpine base. --spider makes a HEAD-like request
# and sets the exit status, which is all HEALTHCHECK needs.
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
    CMD wget -q --spider http://localhost/healthz || exit 1
`;
}

function dockerfileStaticPrebuilt(app) {
  return `${banner('#', app.repo)}#
# ${app.title} — static site, served by nginx.
#
# There is no build stage: ${app.serveDir}/ is committed to the repo already
# built, so the image is the web server plus those files. Adding a Node stage
# here would be inventing work that has no inputs.
${nginxRuntimeStage(app, `COPY ${app.serveDir}/ /usr/share/nginx/html/`)}`;
}

function dockerfileStaticBuild(app) {
  const node = app.nodeVersion || DEFAULT_NODE;
  return `${banner('#', app.repo)}#
# ${app.title} — static site built with Node, served by nginx.

# node:*-slim rather than -alpine on purpose. Several of these builds pull
# native or prebuilt-binary dependencies (esbuild, sharp) whose musl variants
# have been the source of build failures that only appear on one repo at a time.
# The builder stage is discarded, so its size costs nothing in the pulled image.
FROM node:${node}-slim AS builder
WORKDIR /app

# The whole context is copied before install rather than package*.json first.
# The lockfile-only trick caches better, but several of these repos run build
# steps during install that read files elsewhere in the tree, and a partial
# context makes those fail in ways that read as dependency errors.
COPY . .

RUN npm ci
RUN ${app.buildCmd}

${nginxRuntimeStage(app, `COPY --from=builder /app/${app.outDir}/ /usr/share/nginx/html/`)}`;
}

// ---------------------------------------------------------------------------
// service images
// ---------------------------------------------------------------------------

function dockerfileNodeService(app) {
  const node = app.nodeVersion || DEFAULT_NODE;
  const note = app.note ? `#\n# NOTE: ${wrap(app.note, 76, '# ')}\n` : '';
  const portEnv = app.portEnv ? `ENV ${app.portEnv}=${app.port}\n` : '';
  return `${banner('#', app.repo)}#
# ${app.title} — Node service.
${note}
FROM node:${node}-slim AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN ${app.buildCmd}

FROM node:${node}-slim
WORKDIR /app
ENV NODE_ENV=production
${portEnv}
# The whole built tree is copied, node_modules included. These are npm
# workspaces: pruning to production dependencies means re-resolving the
# workspace graph in the runtime stage, and getting that subtly wrong yields an
# image that starts and then throws MODULE_NOT_FOUND on the first request to
# whichever route needed the pruned package. Size is the price of not doing that.
COPY --from=builder /app ./

EXPOSE ${app.port}${(app.extraPorts || []).map((p) => `\nEXPOSE ${p.port}${p.proto === 'udp' ? '/udp' : ''}`).join('')}

# A TCP connect, not an HTTP request against a guessed path. If this app grows a
# /health route the check can be tightened; asserting one that does not exist
# would mark a working container unhealthy forever.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \\
    CMD node -e "require('net').connect(${app.port},'127.0.0.1').on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))" || exit 1

CMD ["node", "${app.serverDir}/dist/index.js"]
`;
}

function dockerfileRustService(app) {
  const note = app.note ? `#\n# NOTE: ${wrap(app.note, 76, '# ')}\n` : '';
  const webStage = app.webBuild
    ? `
# ${app.webBuild.dir}/ builds into ${app.webBuild.outDir}/, which is NOT tracked in
# git. Without this stage the runtime has no UI to serve.
FROM node:${DEFAULT_NODE}-slim AS web
WORKDIR /app
COPY . .
RUN cd ${app.webBuild.dir} && npm ci && ${app.webBuild.cmd}
`
    : '';

  const webCopy = app.webBuild
    ? `COPY --from=web /app/${app.webBuild.outDir} /app/${app.webBuild.outDir}\n`
    : '';

  const cmd = app.cmdArgs
    ? `CMD ["${app.binary}", ${app.cmdArgs.map((a) => `"${a}"`).join(', ')}]`
    : `CMD ["${app.binary}"]`;

  // A bind-mounted appdata directory starts empty and hides anything baked into
  // the image at that path, so a config file COPYed straight to /app/config is
  // invisible on exactly the first run that needs it — the container exits and
  // the user sees a crash loop with no explanation. The defaults are therefore
  // kept somewhere the mount cannot shadow and copied in when the volume is
  // empty.
  const seed = app.seedConfig
    ? `
COPY ${app.seedConfig.from}/ /app/config-default/
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
`
    : '';

  return `${banner('#', app.repo)}#
# ${app.title} — Rust service.
${note}${webStage}
FROM ${RUST_BASE} AS builder
WORKDIR /app

# pkg-config and libssl-dev are not needed by the current dependency set (no
# openssl-sys in Cargo.lock), but cmake and a C toolchain are cheap insurance
# for transitive crates that build vendored C. Remove them if the build proves
# it does not need them.
RUN apt-get update \\
    && apt-get install -y --no-install-recommends build-essential cmake pkg-config \\
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN cargo build --release -p ${app.cargoPackage}

FROM ${RUNTIME_BASE}
RUN apt-get update \\
    && apt-get install -y --no-install-recommends ca-certificates curl \\
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY --from=builder /app/target/release/${app.binary} /usr/local/bin/${app.binary}
${webCopy}
EXPOSE ${app.port}${(app.extraPorts || []).map((p) => `\nEXPOSE ${p.port}${p.proto === 'udp' ? '/udp' : ''}`).join('')}
${app.dataPath ? `VOLUME ["${app.dataPath}"]\n` : ''}${seed}
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
    CMD curl -fsS http://localhost:${app.seedConfig?.bindPortLine ? '\${WEB_PORT:-' + app.port + '}' : app.port}/ >/dev/null || exit 1

${cmd}
`;
}

function entrypointScript(app) {
  return `#!/bin/sh
${banner('#', app.repo)}#
# Seeds ${app.configPath} from the image defaults the first time the container
# runs, then hands off to the real command.
#
# This exists because Unraid points ${app.configPath} at an appdata directory
# that does not exist yet on a first install. Docker creates it empty, and an
# empty bind mount hides whatever the image shipped at that path — so a config
# COPYed to ${app.configPath} at build time is missing precisely when it is
# first needed.

set -e

if [ -d /app/config-default ] && [ -z "$(ls -A ${app.configPath} 2>/dev/null)" ]; then
    echo "entrypoint: ${app.configPath} is empty, seeding defaults"
    mkdir -p ${app.configPath}
    cp -a /app/config-default/. ${app.configPath}/
    # Named for the app rather than left as example.toml, so the file the
    # command line points at is the file that is actually there.
    if [ -f ${app.configPath}/${app.seedConfig.defaultFile} ] && \\
       [ ! -f ${app.configPath}/${app.seedConfig.as} ]; then
        mv ${app.configPath}/${app.seedConfig.defaultFile} ${app.configPath}/${app.seedConfig.as}
    fi${app.seedConfig.bindPortLine ? `

    # Move the web UI off the port the repo's example config uses. This app runs
    # on host networking, where Unraid's port field does nothing and the process
    # binds the host directly — so sharing a default with another host-networked
    # container means whichever starts second dies with EADDRINUSE. flock is
    # already on ${app.seedConfig.bindPortLine.clash}, and was there first.
    #
    # Seed time only: this rewrites the file once, when it is first created. Edit
    # the port in the config afterwards and it stays edited.
    sed -i 's|^bind = "0.0.0.0:${app.seedConfig.bindPortLine.from}"|bind = "0.0.0.0:'"\${WEB_PORT:-${app.port}}"'"|' \\
        ${app.configPath}/${app.seedConfig.as}` : ''}
fi

exec "$@"
`;
}

// ---------------------------------------------------------------------------
// .dockerignore
// ---------------------------------------------------------------------------

function dockerignore(app) {
  // Leading slashes matter. A bare `dist` would also match srt-router's
  // committed demo/dist, which is the entire payload of that image.
  const lines = [
    banner('#', app.repo).trimEnd(),
    '',
    '.git',
    '.github',
    'node_modules',
    '**/node_modules',
    '.DS_Store',
    '*.log',
    '',
    '# Build output. Regenerated inside the image; copying a host build in would',
    '# make the image depend on whatever was last built on someone\'s laptop.',
  ];

  if (app.kind === 'static-build') {
    lines.push(`/${app.outDir}`);
    if (app.variants) for (const v of app.variants) lines.push(`/${v.outDir}`);
    lines.push('/out');
  }
  if (app.kind === 'rust-service') {
    lines.push('/target');
    if (app.webBuild) lines.push(`/${app.webBuild.outDir}`);
  }
  if (app.kind === 'node-service') {
    lines.push('**/dist');
  }
  if (app.kind === 'static-prebuilt') {
    lines.push('# (none — the served directory is committed and must reach the build context)');
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// docker-compose.yml
// ---------------------------------------------------------------------------

function compose(app) {
  const image = `${REGISTRY}/${app.image}:latest`;
  const isStatic = app.kind.startsWith('static');
  const internalPort = isStatic ? 80 : app.port;
  // Taken from unraid.json so a compose run and a CA install land on the same
  // port. Two different defaults for the same app is a support question waiting
  // to happen.
  const hostPort = unraid.apps[app.image]?.hostPort ?? (isStatic ? 8080 : app.port);

  let net;
  if (app.hostNetwork) {
    net = `    # Host networking is not a preference here. ${wrap(
      'This app discovers devices with mDNS/broadcast, and Docker\'s bridge network does not reliably forward multicast. In bridge mode discovery does not error — it simply finds nothing, which reads as "no devices on the network" rather than as a networking problem. Drop this and add a ports: mapping if you would rather add devices by IP and keep the container isolated.',
      74,
      '    # ',
    )}
    network_mode: host`;
  } else {
    const ports = [`      - "${hostPort}:${internalPort}"`];
    for (const p of app.extraPorts || []) {
      ports.push(`      - "${p.port}:${p.port}${p.proto === 'udp' ? '/udp' : ''}"  # ${p.what}`);
    }
    net = `    ports:\n${ports.join('\n')}`;
  }

  const volumes = [];
  if (app.configPath) volumes.push(`      - ./config:${app.configPath}`);
  if (app.dataPath) volumes.push(`      - ${app.image}-data:${app.dataPath}`);

  return `${banner('#', app.repo)}#
# Pull the published image by default. Uncomment build: . to build from this
# checkout instead — useful when testing a change before it reaches GHCR.

services:
  ${app.image}:
    image: ${image}
    # build: .
    container_name: ${app.image}
    restart: unless-stopped
${net}
${volumes.length ? `    volumes:\n${volumes.join('\n')}\n` : ''}${
    app.portEnv ? `    environment:\n      - ${app.portEnv}=${app.port}\n` : ''
  }${
    app.dataPath
      ? `\nvolumes:\n  ${app.image}-data:\n`
      : ''
  }`;
}

// ---------------------------------------------------------------------------
// GitHub Actions workflow
// ---------------------------------------------------------------------------

function workflow(app, allImages) {
  app = { ...app, billsMinutes: billsMinutes(app.repo) };
  const matrix = allImages
    .map(
      (i) =>
        `          - image: ${i.image}\n            dockerfile: ${i.dockerfile}\n            context: .`,
    )
    .join('\n');

  return `${banner('#', app.repo)}#
# Builds the container image(s) for this repo and publishes them to GHCR.
#
# This is the only real verification these images get: there is no container
# runtime on the machine they were authored on, so "it builds" is a claim this
# workflow either proves or disproves. Treat a red run as the image not existing.

name: docker

on:
  push:
    branches: [main, master]
    tags: ['v*']
${app.billsMinutes ? PRIVATE_TRIGGER_NOTE : '  pull_request:'}
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
${matrix}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      # Only log in for pushes. Pull requests from forks have no package write
      # token, and a login step that fails there turns every PR red for a
      # reason that has nothing to do with the change.
      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: \${{ matrix.context }}
          file: \${{ matrix.dockerfile }}
          # Pull requests build but do not publish, so a broken Dockerfile is
          # caught without putting an unreviewed image on the registry.
          push: \${{ github.event_name != 'pull_request' }}
          tags: |
            ${REGISTRY}/\${{ matrix.image }}:latest
            ${REGISTRY}/\${{ matrix.image }}:\${{ github.sha }}
          # Links the GHCR package to this repo. Where the image name already
          # matches the repo name GitHub infers this and the package inherits
          # the repo's public visibility; where it does not — the website
          # publishes stoatworks-website from stoatworks-labs.github.io — the
          # package is left unlinked and stays PRIVATE, so an anonymous
          # docker pull gets a 403 while every other image in the fleet works.
          labels: |
            org.opencontainers.image.source=\${{ github.server_url }}/\${{ github.repository }}
          cache-from: type=gha,scope=\${{ matrix.image }}
          cache-to: type=gha,mode=max,scope=\${{ matrix.image }}
`;
}

// ---------------------------------------------------------------------------

function wrap(text, width, prefix) {
  const words = text.split(/\s+/);
  const lines = [];
  let line = '';
  for (const w of words) {
    if (line && (line + ' ' + w).length > width) {
      lines.push(line);
      line = w;
    } else {
      line = line ? line + ' ' + w : w;
    }
  }
  if (line) lines.push(line);
  return lines.join('\n' + prefix);
}

function readHeaders(repoDir, headersPath) {
  if (!headersPath) return null;
  const full = join(repoDir, headersPath);
  return existsSync(full) ? readFileSync(full, 'utf8') : null;
}

for (const app of fleet.apps) {
  if (ONLY && !ONLY.includes(app.repo)) continue;
  const repoDir = join(PROJECTS, app.repo);
  if (!existsSync(repoDir)) {
    skipped.push(`${app.repo}: directory not found at ${repoDir}`);
    continue;
  }

  const images = [];

  // --- primary image -------------------------------------------------------
  if (app.hasOwnDocker) {
    skipped.push(
      `${app.repo}: Dockerfile/compose/.dockerignore left alone (hasOwnDocker)`,
    );
    images.push({ image: app.image, dockerfile: 'Dockerfile' });
  } else {
    let dockerfile;
    if (app.kind === 'static-prebuilt') dockerfile = dockerfileStaticPrebuilt(app);
    else if (app.kind === 'static-build') dockerfile = dockerfileStaticBuild(app);
    else if (app.kind === 'node-service') dockerfile = dockerfileNodeService(app);
    else if (app.kind === 'rust-service') dockerfile = dockerfileRustService(app);
    else throw new Error(`${app.repo}: unknown kind ${app.kind}`);

    write(repoDir, 'Dockerfile', dockerfile);
    if (app.seedConfig) write(repoDir, 'docker/entrypoint.sh', entrypointScript(app));
    write(repoDir, '.dockerignore', dockerignore(app));
    write(repoDir, 'docker-compose.yml', compose(app));
    images.push({ image: app.image, dockerfile: 'Dockerfile' });

    if (app.kind.startsWith('static')) {
      const { conf, headersSnippet } = generateNginx({
        headersText: readHeaders(repoDir, app.headers),
        notFound: app.notFound,
        repo: app.repo,
        headersPath: app.headers || '(none)',
      });
      write(repoDir, 'docker/nginx.conf', conf);
      write(repoDir, 'docker/stoatworks-headers.conf', headersSnippet);
    }
  }

  // --- build variants (pixel-peeker lite) ---------------------------------
  for (const v of app.variants || []) {
    const variantApp = { ...app, ...v, note: null };
    write(repoDir, `docker/Dockerfile.${v.image}`, dockerfileStaticBuild(variantApp));
    images.push({ image: v.image, dockerfile: `docker/Dockerfile.${v.image}` });
  }

  // --- second image in the same repo (srt-router demo) --------------------
  if (app.extraImage) {
    const extra = { ...app.extraImage, repo: app.repo };
    write(repoDir, `docker/Dockerfile.${extra.image}`, dockerfileStaticPrebuilt(extra));
    // Written under the plain names the runtime stage expects. That is safe
    // because the only repo with a second image is srt-router, whose primary
    // image is the Rust relay and so writes no nginx config to collide with.
    const { conf, headersSnippet } = generateNginx({
      headersText: readHeaders(repoDir, extra.headers),
      notFound: extra.notFound,
      repo: app.repo,
      headersPath: extra.headers || '(none)',
    });
    write(repoDir, 'docker/nginx.conf', conf);
    write(repoDir, 'docker/stoatworks-headers.conf', headersSnippet);
    images.push({ image: extra.image, dockerfile: `docker/Dockerfile.${extra.image}` });
  }

  // An app with hasOwnWorkflow runs its own CI — tests, a multi-arch matrix, a
  // smoke test that boots the image, a release job. Dropping the generated
  // docker.yml alongside it means two workflows racing to push the same tags,
  // and silently overwriting it would delete work this generator knows nothing
  // about. Such a repo is responsible for building and pushing its own image.
  if (app.hasOwnWorkflow) {
    skipped.push(
      `${app.repo}: .github/workflows/docker.yml not written (hasOwnWorkflow) — the repo builds and pushes its own image`,
    );
  } else {
    write(repoDir, '.github/workflows/docker.yml', workflow(app, images));
  }
}

console.log(`\nWrote ${written.length} files.`);
for (const w of written) console.log('  ' + w);
if (skipped.length) {
  console.log(`\nNotes (${skipped.length}):`);
  for (const s of skipped) console.log('  ' + s);
}
